### ISSUE TITLE
Phising site got blocked immedietly when i create a traditional login facebook site, It said: suspected phising site can u bypass or fix that?

### ISSUE THREAD

**Issue by WHdonttry** [KasRoudra/PyPhisher#82] opened 2022-07-12 05:33 UTC

**Comment by KasRoudra** [comment] 2022-07-12 05:36
@WHdonttry Does this happen for both ngrok links and cloudflared links? If so, there is no fix. You should try a different browser

**Comment by WHdonttry** [comment] 2022-07-12 05:42
@KasRoudra yes it is whenever i create a link i didnt even send to anyone there is a ip address pop up that clicked the link already and its in the US this is the ip: 34.83.203.92 Whenever that ip pop up the site got blocked in all ways u can try and fix tho thanks

**Comment by KasRoudra** [comment] 2022-07-12 05:46
@WHdonttry Secured browsers will always block phishing link, we can't fix that. You need to use a different browser like chrome/brave/edge etc. And how many links do you get? You should get 4 links and at least some should bypass warning

**Comment by WHdonttry** [comment] 2022-07-12 06:29
@KasRoudra 1 last thing the ngrok is worked for bypass but i saved the token and successfull created the ngrok server but the ngrok phising link still doesn't work

**Comment by KasRoudra** [comment] 2022-07-12 06:32
@WHdonttry What error do you get with ngrok? Your browser allows ngrok but blocks cloudflared?!

**Comment by WHdonttry** [comment] 2022-07-12 06:35
@KasRoudra no i meant i already had a ngrok account and install auth token but its still appear error_ngrok_6022

**Comment by KasRoudra** [comment] 2022-07-12 06:38
@WHdonttry Run `cat ~/.ngrok2/ngrok.yml` and check whether your token is really set up. Alternatively, generate a new token and then configure it

**Comment by WHdonttry** [comment] 2022-07-12 07:50
I tried all and it didnt work can u record a video about the set up pls?

**Comment by KasRoudra** [comment] 2022-07-12 07:53
@WHdonttry Check instructions here: https://github.com/KasRoudra/PyPhisher/issues/1

**Comment by WHdonttry** [comment] 2022-07-12 08:50
@KasRoudra its worked tysmmm

**Comment by KasRoudra** [comment] 2022-07-12 08:52
@WHdonttry If your issue is solved, you may close this github issue

**Comment by WHdonttry** [comment] 2022-07-12 09:13
@KasRoudra but how to remove the browser warning on ngrok?

**Comment by WHdonttry** [comment] 2022-07-12 09:23
@KasRoudra it keep pop up the browser warning for visitor like: you are about to visit ..ngrok.io i nearly cannot do anything ;-;

**Comment by WHdonttry** [comment] 2022-07-12 10:45
Oof idk why all visiors i sent that link they all got warning

**Comment by KasRoudra** [comment] 2022-07-12 11:08
@WHdonttry Every phishing scripts with ngrok or cloudflared will reproduce this problem. You have to cope with it

**Comment by WHdonttry** [comment] 2022-07-12 11:49
@KasRoudra u know how to change the header in ur own tunnel?

**Comment by KasRoudra** [comment] 2022-07-12 12:28
@WHdonttry What do you mean by header here? The main page is of html, you may edit meta tags. The browsers warns/block due to url. You can't change that url. But I assume a ngrok paid account gives custom domain which may change url

**Closed** 2022-07-28 06:42 UTC
